spring:
  profiles:
    active: local

---
# docker install
# docker pull postgres
# docker run --name querydsl -d -p 5433:5432 -e POSTGRES_PASSWORD="1234" postgres
# docker exec -it querydsl /bin/bash
# psql -U postgres
# CREATE USER querydsl PASSWORD '1234' SUPERUSER;
# CREATE DATABASE querydsl OWNER querydsl;

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5433/querydsl
    username: querydsl
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug