spring:
  config:
    activate:
      on-profile: localhost

  datasource:
    url: jdbc:postgresql://localhost:5432/batch
    username: batch
    password: 1234
    driver-class-name: org.postgresql.Driver

  batch:
    job:
      names: ${job.name:NONE}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

logging.level:
  org.hibernate.SQL: debug